---
abstract: 'Talks and projects by Barcelona.pm'
author:
  - 'Alex Muntada <alexm@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-PM-Barcelona
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0
  DateTime::Event::ICal: 0
  DateTime::Set: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
